### ISSUE TITLE
Missing development environment items

### ISSUE THREAD

**Issue by gregbath** [Ordissimo/libmfp2-canon#1]
I tried to build libmfp2-canon in a newly created Debian 9.9 VM.  

I setup the development environment as described but I get:
"bash: debuild: command not found"
'debuild' can be found in devscripts, pbuilder and xbuilder but which of these should I install or is there some other basic build environment step that is missing?

My target is actually to get this to work in a Fedora 30 environment so if you have any hints on how to build this there it would be much appreciated too.

**Comment by ThierryHFR** [comment]
I created the spec file, see commit [a894c70](https://github.com/Ordissimo/libmfp2-canon/commit/a894c709d0020a3b2516e80d9dfc29e07abf0acd). 
I tested the build on CentOS7.
the rpm-src: https://github.com/Ordissimo/libmfp2-canon/releases/download/0.1/libmfp2-canon-0.1-1.src.rpm

**Comment by ThierryHFR** [comment]
Update REAME.md instalation
