### ISSUE TITLE
Redhat build instructions

### ISSUE THREAD

**Issue by gregbath** [Ordissimo/libmfp2-canon#2]
There are a couple of errors in the Redhat build instructions on my Fedora 30 x86_64 system..

(1) The tar line in the second solution is missing the source directory from the end of the command line
..........
tar czvf  libmfp2-canon-0.1.orig.tar.gz **libmfp2-canon-0.1**
..........
(2) The created rpm files are in an x86_64 subdirectory.
........
cd ~/rpmbuild/RPMS
rpm -i libmfp2-canon-0.1*.rpm
.......
could either be
`cd ~/rpmbuild/RPMS/x86_64`
or
`rpm -i */libmfp2-canon-0.1*.rpm`

**Comment by ThierryHFR** [comment]
Thanks for the return, I updated the readme.
Can you give me a return for below.
Sorrt, I do not know much redhat.

Replace the order:
tar czvf libmfp2-canon-0.1.orig.tar.gz libmfp2-canon-0.1
by:
tar -czvf libmfp2-canon-0.1.orig.tar.gz libmfp2-canon-0.1

**Comment by gregbath** [comment]
The issue was that the directory name libmfp2-canon-0.1 was left off the end of the tar command line.

Both the tar czvf and tar -czvf  command line formats work on F30.

**Comment by ThierryHFR** [comment]
Thank you, corrected :)
