### ISSUE TITLE
cnijfilter2 source code for canon pixma

### ISSUE THREAD

**Issue by coiouhkc** [Ordissimo/libmfp2-canon#20]
Hi Thierry @Ordissimo  and sorry for the offtopic, but i could not find another way to contact you.
If i'm correct, you're the maintainer of the cnijfilter2 on launchpad ppa for bionic - how do i get a version for impish?
If there's anything i could support you with on the way to publishing the package, please let me know.
Thanks in advance and best regards.

**Comment by ThierryHFR** [comment]
Hi @coiouhkc,
Sorry, I've been very busy.
cnijfilter2, scangearmp2 and libmfp2-canon are now available on launchpad.
I will continue in the next days !
