### ISSUE TITLE
Error my backend :	data is invalid (includes no dev at open)

### ISSUE THREAD

**Issue by gregbath** [Ordissimo/libmfp2-canon#3]
Sane library cannot find my scanner but the standard Canon program scangearmp2 can.

Getting the error message in the title when I enable debugging and run scanimage.
`SANE_DEBUG_canon_pixma=255 SANE_DEBUG_DLL=255 scanimage -L`
`[dll] load: searching backend `canon_pixma' in `/usr/lib64/sane'
[dll] load: trying to load `/usr/lib64/sane/libsane-canon_pixma.so.1'
[dll] load: dlopen()ing `/usr/lib64/sane/libsane-canon_pixma.so.1'
[dll] init: initializing backend `canon_pixma'
Error my backend :	data is invalid (includes no dev at open)
`
I managed to trace the error to the canon_mfp2.conf file which does not appear to get its path set from CNMSLIBPATH

**Comment by ThierryHFR** [comment]
I correct the bug.

**Comment by gregbath** [comment]
> I correct the bug.

Thank you.  I should have said that I got everything working by manually adding the path to that file into line  118 of canon_mfp_tools.c
       char *path = "/usr/lib64/bjlib/";
This is a hack but I then managed to prove that the scanner could be found and used via sane.

**Comment by ThierryHFR** [comment]
Yes, great news. I'm trying to find the installation path for all bones.
I'll close the issue when it's done.
Thank you for your return.

**Comment by ThierryHFR** [comment]
Here corrected, can you confirm?

**Comment by gregbath** [comment]
No change at all.

How is the find command you added into configure.ac supposed to work?  Is it the same as the standard linux find command or a special automake syntax? If it is standard linux find then that syntax does not find anything if I run it from the ~rpmbuild directory.

**path_bjlib=$(find -iname "bjlib")**
AC_DEFINE(CNMSLIBPATH, [$path_bjlib], [Pat of bjlib in os])
AC_SUBST(CNMSLIBPATH)

**Comment by ThierryHFR** [comment]
Can you give me the result of the console command:
find -iname "bjlib"

**Comment by gregbath** [comment]
From the build directory: /home/Greg/rpmbuild
[rpmbuild]$ find -iname "bjlib" 
[rpmbuild]$ 

If search is done from the root directory
[rpmbuild]$ find / -xdev -iname "bjlib" 2>/dev/null
/usr/lib64/bjlib
[rpmbuild]$

**Comment by ThierryHFR** [comment]
I just finished the fix.
I'm waiting for your return, thank you!

**Comment by gregbath** [comment]
Thankyou. Fixed.  The scanner is now found.
I initially tried the 'first solution' for downloading the sources but that just gave me the old source code.  When I used the 'second solution' it all works.

I don't seem to be able to set the scanner resolution with 'simple-scan' but I will raise a separate issue if needed.

**Comment by ThierryHFR** [comment]
Can you tell me the source rpm located in "rpmbuild/SRPMS/libmfp2-canon-0.1-1.src.rpm"
I would add it to the git
use to send file : https://send.firefox.com/
Thank you

**Comment by gregbath** [comment]
https://send.firefox.com/download/1cc8ad4f0a4d1844/#uknqmLKZFHx5OfgykBLoGg

**Comment by ThierryHFR** [comment]
Add to the release.
Thank you
