### ISSUE TITLE
No secret key

### ISSUE THREAD

**Issue by pavelkq** [Ordissimo/libmfp2-canon#5]
OS Debian x64. During **$sudo debuild -tc** I've got the error:
Now signing changes and any dsc files...
 signfile dsc libmfp2-canon_0.1.dsc Thierry HUCHARD <thierry@ordissimo.com>
gpg: skiped  "Thierry HUCHARD <thierry@ordissimo.com>": No secret key
gpg: /tmp/debsign.3bwIyzv9/libmfp2-canon_0.1.dsc: clear-sign failed: No secret key
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1112:
running debsign failed

How can I add the signfile?

**Comment by ThierryHFR** [comment]
Hi @pavelkq ,
This is my key, it is only necessary if you broadcast the binaries.
To avoid this message being used:
`sudo debuild -i -us -uc -b`

**Comment by pavelkq** [comment]
Yes - It works! But SANE can't see my CANON scanner(( Just **scangearmp** works well.

**Comment by ThierryHFR** [comment]
Ok, it's been a while since I've updated the code for this project. [New commit](https://github.com/Ordissimo/libmfp2-canon/commit/5a6b0ceb51762555c5e3f014c37aa156f82cc97e)
I've added what's needed to support version 4.10.
Can you rebuild it and tell me if it's ok?

**Comment by ThierryHFR** [comment]
These changes add support for sources, resolution and paper size.

**Comment by pavelkq** [comment]
I've just repeated the installation process by steps, but haven't got result:
```
$ sudo sane-find-scanner 

  # sane-find-scanner will now attempt to detect your scanner. If the
  # result is different from what you expected, first make sure your
  # scanner is powered up and properly connected to your computer.

  # No SCSI scanners found. If you expected something different, make sure that
  # you have loaded a kernel SCSI driver for your SCSI adapter.

found USB scanner (vendor=0x04a9 [Canon], product=0x1793 [MB2100 series]) at libusb:003:003
  # Your USB scanner was (probably) detected. It may or may not be supported by
  # SANE. Try scanimage -L and read the backend's manpage.

  # Not checking for parallel port scanners.

  # Most Scanners connected to the parallel port or other proprietary ports
  # can't be detected by this program.
$ sudo scanimage -Lv
[bjnp] create_broadcast_socket: ERROR - bind socket to local address failed - Cannot assign requested address
Error my backend :	out of memory

No scanners were identified. If you were expecting something different,
check that the scanner is plugged in, turned on and detected by the
sane-find-scanner tool (if appropriate). Please read the documentation
which came with this software (README, FAQ, manpages).
```

**Comment by ThierryHFR** [comment]
What is your version of debian?

**Comment by pavelkq** [comment]
It's debian 10.8 (x86-64), kernel 4.19.0-14-amd64

**Comment by ThierryHFR** [comment]
Hi @pavelkq ,
Can you test with my version of scangearmp2, it contains the backend for Sane ?
https://github.com/Ordissimo/scangearmp2/releases/tag/v4.11
```
sudo apt purge libmfp2-canon scangermp2
sudo apt install  ./scangearmp2_4.11_amd64.deb
```

**Comment by pavelkq** [comment]
I've done it. And I've found the interesting case. I entered `$sudo scanimage -Lv` and remembered that scanner had not been turned on. I turned it on immediately and it was found. I tried to start the Simple scanner program but it couldn't see the scanner. I entered `$sudo scanimage -Lv` again and it didn't work now.

```
[bjnp] create_broadcast_socket: ERROR - bind socket to local address failed - Cannot assign requested address
Error my backend :	out of memory
No scanners were identified. If you were expecting something different,
check that the scanner is plugged in, turned on and detected by the
sane-find-scanner tool (if appropriate). Please read the documentation
which came with this software (README, FAQ, manpages).
```

 I repeated the steps and everything repeated. What does it mean?

By the way on another linux distributive (Live CD AltLinux based on MandrakeLinux) this scanner works well.

**Comment by ThierryHFR** [comment]
Thanks for the test:
Can you edit the file /etc/sane.d/dll.conf
and comment on the line containing :
`pixma`
in
`# pixma`

then test again, turn off your scanner and turn it back on.

**Comment by pavelkq** [comment]
Thank you for helping! 
I did it. Scanner stopped work. And it din't depend on turning on. Then I returned dll.conf in first state. But scanner doesn't work yet in any case.

**Comment by ThierryHFR** [comment]
Ok, from what I see it is your version of sane that is corrupt!
I propose you to build the binary packages from the latest version of sane-backends. The sane project proposes binary for Ubuntu but not for debian (the lauchpad is restrictive).
https://launchpad.net/~sane-project
Your device was added 2 years ago and is supported by the PIXMA driver : [This commit](https://gitlab.com/sane-project/backends/-/commit/8c340a34a49312a29f959e22286c3b83be9bf19b)
```
sudo apt-get install build-essential fakeroot devscripts haskell-debian-utils
dget https://launchpad.net/~sane-project/+archive/ubuntu/sane-release/+sourcefiles/sane-backends/1.0.32-bionic0/sane-backends_1.0.32-bionic0.dsc
cd sane-backends-1.0.31
sudo mk-build-deps --install debian/control
debuild -tc
sudo apt install ../libsane_*.deb ../libsane1_*.deb ../libsane-common_*.deb sane-utils_*.deb
```

**Comment by pavelkq** [comment]
I had security issues while running the dget command. Then I tried to install the sane-beckends in other ways. But nothing happened. Then I decided to upgrade to bullseye version (it contains 1.0.31 version of sane). Now my scanner works fine! Thank you!

**Comment by ThierryHFR** [comment]
Great!
